/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kafka.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MigrationData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7495916824439655559L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MigrationData\",\"namespace\":\"com.kafka.avro\",\"fields\":[{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"fruits\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Fruit\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"color\",\"type\":\"string\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MigrationData> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MigrationData> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MigrationData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MigrationData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MigrationData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MigrationData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MigrationData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MigrationData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MigrationData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence type;
  private java.util.List<com.kafka.avro.Fruit> fruits;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MigrationData() {}

  /**
   * All-args constructor.
   * @param type The new value for type
   * @param fruits The new value for fruits
   */
  public MigrationData(java.lang.CharSequence type, java.util.List<com.kafka.avro.Fruit> fruits) {
    this.type = type;
    this.fruits = fruits;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return type;
    case 1: return fruits;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: type = (java.lang.CharSequence)value$; break;
    case 1: fruits = (java.util.List<com.kafka.avro.Fruit>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'fruits' field.
   * @return The value of the 'fruits' field.
   */
  public java.util.List<com.kafka.avro.Fruit> getFruits() {
    return fruits;
  }


  /**
   * Sets the value of the 'fruits' field.
   * @param value the value to set.
   */
  public void setFruits(java.util.List<com.kafka.avro.Fruit> value) {
    this.fruits = value;
  }

  /**
   * Creates a new MigrationData RecordBuilder.
   * @return A new MigrationData RecordBuilder
   */
  public static com.kafka.avro.MigrationData.Builder newBuilder() {
    return new com.kafka.avro.MigrationData.Builder();
  }

  /**
   * Creates a new MigrationData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MigrationData RecordBuilder
   */
  public static com.kafka.avro.MigrationData.Builder newBuilder(com.kafka.avro.MigrationData.Builder other) {
    if (other == null) {
      return new com.kafka.avro.MigrationData.Builder();
    } else {
      return new com.kafka.avro.MigrationData.Builder(other);
    }
  }

  /**
   * Creates a new MigrationData RecordBuilder by copying an existing MigrationData instance.
   * @param other The existing instance to copy.
   * @return A new MigrationData RecordBuilder
   */
  public static com.kafka.avro.MigrationData.Builder newBuilder(com.kafka.avro.MigrationData other) {
    if (other == null) {
      return new com.kafka.avro.MigrationData.Builder();
    } else {
      return new com.kafka.avro.MigrationData.Builder(other);
    }
  }

  /**
   * RecordBuilder for MigrationData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MigrationData>
    implements org.apache.avro.data.RecordBuilder<MigrationData> {

    private java.lang.CharSequence type;
    private java.util.List<com.kafka.avro.Fruit> fruits;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kafka.avro.MigrationData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.fruits)) {
        this.fruits = data().deepCopy(fields()[1].schema(), other.fruits);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing MigrationData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kafka.avro.MigrationData other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.fruits)) {
        this.fruits = data().deepCopy(fields()[1].schema(), other.fruits);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.kafka.avro.MigrationData.Builder setType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.kafka.avro.MigrationData.Builder clearType() {
      type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'fruits' field.
      * @return The value.
      */
    public java.util.List<com.kafka.avro.Fruit> getFruits() {
      return fruits;
    }


    /**
      * Sets the value of the 'fruits' field.
      * @param value The value of 'fruits'.
      * @return This builder.
      */
    public com.kafka.avro.MigrationData.Builder setFruits(java.util.List<com.kafka.avro.Fruit> value) {
      validate(fields()[1], value);
      this.fruits = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'fruits' field has been set.
      * @return True if the 'fruits' field has been set, false otherwise.
      */
    public boolean hasFruits() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'fruits' field.
      * @return This builder.
      */
    public com.kafka.avro.MigrationData.Builder clearFruits() {
      fruits = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MigrationData build() {
      try {
        MigrationData record = new MigrationData();
        record.type = fieldSetFlags()[0] ? this.type : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.fruits = fieldSetFlags()[1] ? this.fruits : (java.util.List<com.kafka.avro.Fruit>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MigrationData>
    WRITER$ = (org.apache.avro.io.DatumWriter<MigrationData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MigrationData>
    READER$ = (org.apache.avro.io.DatumReader<MigrationData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.type);

    long size0 = this.fruits.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.kafka.avro.Fruit e0: this.fruits) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);

      long size0 = in.readArrayStart();
      java.util.List<com.kafka.avro.Fruit> a0 = this.fruits;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.kafka.avro.Fruit>((int)size0, SCHEMA$.getField("fruits").schema());
        this.fruits = a0;
      } else a0.clear();
      SpecificData.Array<com.kafka.avro.Fruit> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.kafka.avro.Fruit>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.kafka.avro.Fruit e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.kafka.avro.Fruit();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<com.kafka.avro.Fruit> a0 = this.fruits;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.kafka.avro.Fruit>((int)size0, SCHEMA$.getField("fruits").schema());
            this.fruits = a0;
          } else a0.clear();
          SpecificData.Array<com.kafka.avro.Fruit> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.kafka.avro.Fruit>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.kafka.avro.Fruit e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.kafka.avro.Fruit();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










